name: attendance_tracka
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
   sdk: ">=2.6.0 <3.0.0"

dependencies:
   flutter:
      sdk: flutter
   shimmer: ^1.0.1
   flushbar: ^1.9.1

   get_it: ^2.0.1
   # Bloc for state management
   flutter_bloc: ^3.2.0
   hydrated_bloc: ^3.0.0
   # Value equality
   equatable: ^1.0.1
   #Network Connection
   connectivity: ^0.4.6+1
   rxdart: ^0.23.1
   dio: ^3.0.7
   # OS specific path
   path_provider: ^1.3.0
   # Local cache
   hive: ^1.2.0
   hive_flutter: ^0.2.1
   # Input validators
   validators: ^2.0.0+1
   # immutable classes or something like that
   built_value: ^7.0.0
   # barcode scanner
   flutter_camera_ml_vision: ^2.2.5
   # url Launchers
   url_launcher: ^5.4.1

dev_dependencies:
   flutter_test:
      sdk: flutter
   hive_generator: ^0.6.0
   build_runner: ^1.7.2
   built_value_generator: ^7.0.0
   flutter_launcher_icons: ^0.7.2+1

flutter:
   uses-material-design: true
   assets:
      - assets/
   fonts:
      - family: Raleway
        fonts:
           - asset: assets/fonts/raleway/Raleway-Regular.ttf
           - asset: assets/fonts/raleway/Raleway-Black.ttf
             weight: 900
           - asset: assets/fonts/raleway/Raleway-Bold.ttf
             weight: 700
           - asset: assets/fonts/raleway/Raleway-Light.ttf
             weight: 300

      - family: AppIcons
        fonts:
           - asset: assets/fonts/tracka_icons.ttf
